# Valkey Database Connection Parameters.
valkey:
  host: ${VALKEY_HOST}
  port: ${VALKEY_PORT}
  password: ${VALKEY_PASSWORD}
  caCertPath: ${VALKEY_CA_CERT_PATH}
  caCertPassword: ${VALKEY_CA_CERT_PASSWORD}
  userCertPath: ${VALKEY_USER_CERT_PATH}
  userCertPassword: ${VALKEY_USER_CERT_PASSWORD}

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${SSL_CERTIFICATE_PATH}
    key-store-password: ${SSL_CERTIFICATE_PASSWORD}

spring:
  application:
    name: backend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/photoatom?ssl=true&sslmode=verify-ca&sslrootcert=${PSQL_CA_CERT_PATH}&sslcert=${PSQL_USER_CERT_PATH}&sslkey=${PSQL_USER_CERT_KEY_PATH}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop

